{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fmodern Courier New;}{\f1\fmodern\fcharset0 Courier New;}{\f2\fnil\fcharset129 Courier New;}}
{\colortbl ;\red0\green0\blue0;\red48\green127\blue48;\red127\green127\blue27;\red127\green27\blue127;\red27\green127\blue127;\red64\green64\blue127;}
\viewkind4\uc1\pard\f0\fs18 e1-313-15127@10.192.13.11's password:\cf1\highlight1 
\par \cf0\highlight0      \u9484?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9488?\cf1\highlight1 
\par \cf0\highlight0      \u9474?                        \cf2\f1\bullet  MobaXterm 11.1 \bullet  \cf0\f0                          \u9474?\cf1\highlight1 
\par \cf0\highlight0      \u9474?            \cf3 (SSH client, X-server and networking tools)\cf0              \u9474?\cf1\highlight1 
\par \cf0\highlight0      \u9474?                                                                    \u9474?\cf1\highlight1 
\par \cf0\highlight0      \u9474? \u8594? SSH session to \cf4 e1-313-15127\cf0 @\cf4 10.192.13.11                         \cf0\u9474?\cf1\highlight1 
\par \cf0\highlight0      \u9474?\f1    \bullet  SSH compression : \cf2\f0 v\cf0                                             \u9474?\cf1\highlight1 
\par \cf0\highlight0      \u9474?\f1    \bullet  SSH-browser     : \cf2\f0 v\cf0                                             \u9474?\cf1\highlight1 
\par \cf0\highlight0      \u9474?\f1    \bullet  X11-forwarding  : \cf2\f0 v\cf0   (remote display is forwarded through SSH) \u9474?\cf1\highlight1 
\par \cf0\highlight0      \u9474?\f1    \bullet  DISPLAY         : \cf2\f0 v\cf0   (automatically set on remote server)      \u9474?\cf1\highlight1 
\par \cf0\highlight0      \u9474?                                                                    \u9474?\cf1\highlight1 
\par \cf0\highlight0      \u9474? \u8594? For more info, ctrl+click on \cf5\ul help\cf0\ulnone  or visit our \cf5\ul website\cf0\ulnone            \u9474?\cf1\highlight1 
\par \cf0\highlight0      \u9492?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9496?\cf1\highlight1 
\par 
\par \cf0\highlight0 Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-139-generic x86_64)\cf1\highlight1 
\par 
\par \cf0\highlight0  * Documentation:  https://help.ubuntu.com\cf1\highlight1 
\par \cf0\highlight0  * Management:     https://landscape.canonical.com\cf1\highlight1 
\par \cf0\highlight0  * Support:        https://ubuntu.com/advantage\cf1\highlight1 
\par 
\par \cf0\highlight0  System information disabled due to load higher than 32.0\cf1\highlight1 
\par 
\par \cf0\highlight0 155 packages can be updated.\cf1\highlight1 
\par \cf0\highlight0 0 updates are security updates.\cf1\highlight1 
\par 
\par \cf0\highlight0 New release '18.04.2 LTS' available.\cf1\highlight1 
\par \cf0\highlight0 Run 'do-release-upgrade' to upgrade to it.\cf1\highlight1 
\par 
\par \cf0\highlight0 *** System restart required ***\cf1\highlight1 
\par 
\par \cf0\highlight0 Please see this page on the student wiki on usage policy:\cf1\highlight1 
\par \cf0\highlight0 http://clweb.csa.iisc.ernet.in/wiki/doku.php\cf1\highlight1 
\par 
\par \cf0\highlight0 Please clear up any unnecessarily files/folders. We are\cf1\highlight1 
\par \cf0\highlight0 current short of space on /storage.\cf1\highlight1 
\par 
\par \cf0\highlight0 Last login: Wed Mar 20 15:28:39 2019 from 10.3.1.133\cf1\highlight1 
\par \cf0\highlight0 /usr/bin/xauth:  file /home2/e1-313-15127/.Xauthority does not exist\cf1\highlight1 
\par \cf0\highlight0 (base) e1-313-15127@clserv:~$ git clone --single-branch --branch akshayamukundan https://github.com/akshayaamukundan/tipr-t           hird-assignment.git\cf1\highlight1 
\par \cf0\highlight0 Cloning into 'tipr-third-assignment'...\cf1\highlight1 
\par \cf0\highlight0 remote: Enumerating objects: 58, done.\cf1\highlight1 
\par \cf0\highlight0 remote: Counting objects: 100% (58/58), done.\cf1\highlight1 
\par \cf0\highlight0 remote: Compressing objects: 100% (52/52), done.\cf1\highlight1 
\par \cf0\highlight0 remote: Total 146 (delta 16), reused 0 (delta 0), pack-reused 88\cf1\highlight1 
\par \cf0\highlight0 Receiving objects: 100% (146/146), 174.14 MiB | 6.27 MiB/s, done.\cf1\highlight1 
\par \cf0\highlight0 Resolving deltas: 100% (24/24), done.\cf1\highlight1 
\par \cf0\highlight0 Checking connectivity... done.\cf1\highlight1 
\par \cf0\highlight0 (base) e1-313-15127@clserv:~$ conda activate tensorflow\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~$ python3 "/storage2/home2/e1-313-15521/tipr-third-assignment/src/testmain.py" --train-da           ta /storage2/home2/e1-313-15521/tipr-third-assignment/data --test-data /storage2/home2/e1-313-15521/tipr-third-assignment/d           ata --dataset Fashion-MNIST --filter-config [5 5] --activation tanh\cf1\highlight1 
\par \cf0\highlight0 ^CTraceback (most recent call last):\cf1\highlight1 
\par \cf0\highlight0   File "/storage2/home2/e1-313-15521/tipr-third-assignment/src/testmain.py", line 3, in <module>\cf1\highlight1 
\par \cf0\highlight0     import tensorflow as tf\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/__init__.py", line 22, in <mod           ule>\cf1\highlight1 
\par \cf0\highlight0     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 52,            in <module>\cf1\highlight1 
\par \cf0\highlight0     from tensorflow.core.framework.graph_pb2 import *\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/core/framework/graph_pb2.py",            line 6, in <module>\cf1\highlight1 
\par \cf0\highlight0     from google.protobuf import descriptor as _descriptor\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/google/protobuf/__init__.py", line 37, in            <module>\cf1\highlight1 
\par \cf0\highlight0     __import__('pkg_resources').declare_namespace(__name__)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in            <module>\cf1\highlight1 
\par \cf0\highlight0     @_call_aside\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3110, in            _call_aside\cf1\highlight1 
\par \cf0\highlight0     f(*args, **kwargs)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3139, in            _initialize_master_working_set\cf1\highlight1 
\par \cf0\highlight0     working_set = WorkingSet._build_master()\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in            _build_master\cf1\highlight1 
\par \cf0\highlight0     ws = cls()\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in            __init__\cf1\highlight1 
\par \cf0\highlight0     self.add_entry(entry)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 621, in            add_entry\cf1\highlight1 
\par \cf0\highlight0     for dist in find_distributions(entry, True):\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1968, in            find_on_path\cf1\highlight1 
\par \cf0\highlight0     for dist in factory(fullpath):\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2038, in            distributions_from_metadata\cf1\highlight1 
\par \cf0\highlight0     root, entry, metadata, precedence=DEVELOP_DIST,\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2495, in            from_location\cf1\highlight1 
\par \cf0\highlight0     py_version=py_version, platform=platform, **kw\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2870, in            _reload_version\cf1\highlight1 
\par \cf0\highlight0     md_version = _version_from_file(self._get_metadata(self.PKG_INFO))\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2459, in            _version_from_file\cf1\highlight1 
\par \cf0\highlight0     line = next(iter(version_lines), '')\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2649, in            _get_metadata\cf1\highlight1 
\par \cf0\highlight0     for line in self.get_metadata_lines(name):\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1814, in            get_metadata_lines\cf1\highlight1 
\par \cf0\highlight0     return yield_lines(self.get_metadata(name))\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1801, in            get_metadata\cf1\highlight1 
\par \cf0\highlight0     metadata = f.read()\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/codecs.py", line 318, in decode\cf1\highlight1 
\par \cf0\highlight0     def decode(self, input, final=False):\cf1\highlight1 
\par \cf0\highlight0 KeyboardInterrupt\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~$ python3 "../tipr-third-assignment/src/main.py" --train-data ../data --test-data ../data            --dataset Fashion-MNIST --filter-config [5 5] --activation tanh                                                                      python3: can't open file '../tipr-third-assignment/src/main.py': [Errno 2] No such file or directory\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~$ python3 "tipr-third-assignment/src/main.py" --train-data ../data --test-data ../data --           dataset Fashion-MNIST --filter-config [5 5] --activation tanh\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From tipr-third-assignment/src/main.py:205: softmax_cross_entropy_with_logits (from tensorflow.python.op           s.nn_ops) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par 
\par \cf0\highlight0 Future major versions of TensorFlow will allow gradients to flow\cf1\highlight1 
\par \cf0\highlight0 into the labels input on backprop by default.\cf1\highlight1 
\par 
\par \cf0\highlight0 See @\{tf.nn.softmax_cross_entropy_with_logits_v2\}.\cf1\highlight1 
\par 
\par \cf0\highlight0 2019-03-20 16:21:16.113849: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this T           ensorFlow binary was not compiled to use: AVX2 FMA\cf1\highlight1 
\par \cf0\highlight0 epoch: 0\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From tipr-third-assignment/src/main.py:50: read_data_sets (from tensorflow.contrib.learn.python.learn.da           tasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use alternatives such as official/mnist/dataset.py from tensorflow/models.\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/           python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated            and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please write your own downloading logic.\cf1\highlight1 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight1 
\par \cf0\highlight0   File "tipr-third-assignment/src/main.py", line 220, in <module>\cf1\highlight1 
\par \cf0\highlight0     myobject.datasetextract(b, trainpath, datasetName)\cf1\highlight1 
\par \cf0\highlight0   File "tipr-third-assignment/src/main.py", line 50, in datasetextract\cf1\highlight1 
\par \cf0\highlight0     datafmnist = input_data.read_data_sets(file1, one_hot=True)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", l           ine 272, in new_func\cf1\highlight1 
\par \cf0\highlight0     return func(*args, **kwargs)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/dat           asets/mnist.py", line 260, in read_data_sets\cf1\highlight1 
\par \cf0\highlight0     source_url + TRAIN_IMAGES)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", l           ine 272, in new_func\cf1\highlight1 
\par \cf0\highlight0     return func(*args, **kwargs)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/dat           asets/base.py", line 249, in maybe_download\cf1\highlight1 
\par \cf0\highlight0     gfile.MakeDirs(work_directory)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", lin           e 379, in recursive_create_dir\cf1\highlight1 
\par \cf0\highlight0     pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(dirname), status)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.p           y", line 519, in __exit__\cf1\highlight1 
\par \cf0\highlight0     c_api.TF_GetCode(self.status.status))\cf1\highlight1 
\par \cf0\highlight0 tensorflow.python.framework.errors_impl.PermissionDeniedError: ../data; Permission denied\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~$ python3 "tipr-third-assignment/src/main.py" --train-data tipr-third-assignment/data --test-data tipr-third-assignment/data --dataset Fashion-MNIST --filter-config [5 5] --activation tanh\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From tipr-third-assignment/src/main.py:205: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par 
\par \cf0\highlight0 Future major versions of TensorFlow will allow gradients to flow\cf1\highlight1 
\par \cf0\highlight0 into the labels input on backprop by default.\cf1\highlight1 
\par 
\par \cf0\highlight0 See @\{tf.nn.softmax_cross_entropy_with_logits_v2\}.\cf1\highlight1 
\par 
\par \cf0\highlight0 2019-03-20 16:28:59.530939: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\cf1\highlight1 
\par \cf0\highlight0 epoch: 0\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From tipr-third-assignment/src/main.py:50: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use alternatives such as official/mnist/dataset.py from tensorflow/models.\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please write your own downloading logic.\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use tf.data to implement this functionality.\cf1\highlight1 
\par \cf0\highlight0 Extracting tipr-third-assignment/data/Fashion-MNIST/train-images-idx3-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use tf.data to implement this functionality.\cf1\highlight1 
\par \cf0\highlight0 Extracting tipr-third-assignment/data/Fashion-MNIST/train-labels-idx1-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:110: dense_to_one_hot (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use tf.one_hot on tensors.\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:252: _internal_retry.<locals>.wrap.<locals>.wrapped_fn (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use urllib or similar directly.\cf1\highlight1 
\par \cf0\highlight0 Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.\cf1\highlight1 
\par \cf0\highlight0 Extracting tipr-third-assignment/data/Fashion-MNIST/t10k-images-idx3-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.\cf1\highlight1 
\par \cf0\highlight0 Extracting tipr-third-assignment/data/Fashion-MNIST/t10k-labels-idx1-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use alternatives such as official/mnist/dataset.py from tensorflow/models.\cf1\highlight1 
\par \cf0\highlight0 Validation test accuracy :: 0.866909090909091\cf1\highlight1 
\par \cf0\highlight0 Validation test Macro F1 Score:: 0.8665583116737217\cf1\highlight1 
\par \cf0\highlight0 Validation test Micro F1 Score:: 0.866909090909091\cf1\highlight1 
\par \cf0\highlight0 2019-03-20 16:35:50.735692: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at save_restore_v2_ops.cc:109 : Not found: ../Models/Fashion-MNIST; No such file or directory\cf1\highlight1 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call\cf1\highlight1 
\par \cf0\highlight0     return fn(*args)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn\cf1\highlight1 
\par \cf0\highlight0     options, feed_dict, fetch_list, target_list, run_metadata)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun\cf1\highlight1 
\par \cf0\highlight0     run_metadata)\cf1\highlight1 
\par \cf0\highlight0 tensorflow.python.framework.errors_impl.NotFoundError: ../Models/Fashion-MNIST; No such file or directory\cf1\highlight1 
\par \cf0\highlight0          [[Node: save/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, W0, W0/Adam, W0/Adam_1, W1, W1/Adam, W1/Adam_1, batch_normalization/beta, batch_normalization/beta/Adam, batch_normalization/beta/Adam_1, batch_normalization/gamma, batch_normalization/gamma/Adam, batch_normalization/gamma/Adam_1, batch_normalization/moving_mean, batch_normalization/moving_variance, batch_normalization_1/beta, batch_normalization_1/beta/Adam, batch_normalization_1/beta/Adam_1, batch_normalization_1/gamma, batch_normalization_1/gamma/Adam, batch_normalization_1/gamma/Adam_1, batch_normalization_1/moving_mean, batch_normalization_1/moving_variance, batch_normalization_2/beta, batch_normalization_2/beta/Adam, batch_normalization_2/beta/Adam_1, batch_normalization_2/gamma, batch_normalization_2/gamma/Adam, batch_normalization_2/gamma/Adam_1, batch_normalization_2/moving_mean, batch_normalization_2/moving_variance, batch_normalization_3/beta, batch_normalization_3/beta/Adam, batch_normalization_3/beta/Adam_1, batch_normalization_3/gamma, batch_normalization_3/gamma/Adam, batch_normalization_3/gamma/Adam_1, batch_normalization_3/moving_mean, batch_normalization_3/moving_variance, beta1_power, beta2_power, fully_connected/biases, fully_connected/biases/Adam, fully_connected/biases/Adam_1, fully_connected/weights, fully_connected/weights/Adam, fully_connected/weights/Adam_1, fully_connected_1/biases, fully_connected_1/biases/Adam, fully_connected_1/biases/Adam_1, fully_connected_1/weights, fully_connected_1/weights/Adam, fully_connected_1/weights/Adam_1, fully_connected_2/biases, fully_connected_2/biases/Adam, fully_connected_2/biases/Adam_1, fully_connected_2/weights, fully_connected_2/weights/Adam, fully_connected_2/weights/Adam_1)]]\cf1\highlight1 
\par 
\par \cf0\highlight0 During handling of the above exception, another exception occurred:\cf1\highlight1 
\par 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1620, in save\cf1\highlight1 
\par \cf0\highlight0     \{self.saver_def.filename_tensor_name: checkpoint_file\})\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run\cf1\highlight1 
\par \cf0\highlight0     run_metadata_ptr)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run\cf1\highlight1 
\par \cf0\highlight0     feed_dict_tensor, options, run_metadata)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run\cf1\highlight1 
\par \cf0\highlight0     run_metadata)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call\cf1\highlight1 
\par \cf0\highlight0     raise type(e)(node_def, op, message)\cf1\highlight1 
\par \cf0\highlight0 tensorflow.python.framework.errors_impl.NotFoundError: ../Models/Fashion-MNIST; No such file or directory\cf1\highlight1 
\par \cf0\highlight0          [[Node: save/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, W0, W0/Adam, W0/Adam_1, W1, W1/Adam, W1/Adam_1, batch_normalization/beta, batch_normalization/beta/Adam, batch_normalization/beta/Adam_1, batch_normalization/gamma, batch_normalization/gamma/Adam, batch_normalization/gamma/Adam_1, batch_normalization/moving_mean, batch_normalization/moving_variance, batch_normalization_1/beta, batch_normalization_1/beta/Adam, batch_normalization_1/beta/Adam_1, batch_normalization_1/gamma, batch_normalization_1/gamma/Adam, batch_normalization_1/gamma/Adam_1, batch_normalization_1/moving_mean, batch_normalization_1/moving_variance, batch_normalization_2/beta, batch_normalization_2/beta/Adam, batch_normalization_2/beta/Adam_1, batch_normalization_2/gamma, batch_normalization_2/gamma/Adam, batch_normalization_2/gamma/Adam_1, batch_normalization_2/moving_mean, batch_normalization_2/moving_variance, batch_normalization_3/beta, batch_normalization_3/beta/Adam, batch_normalization_3/beta/Adam_1, batch_normalization_3/gamma, batch_normalization_3/gamma/Adam, batch_normalization_3/gamma/Adam_1, batch_normalization_3/moving_mean, batch_normalization_3/moving_variance, beta1_power, beta2_power, fully_connected/biases, fully_connected/biases/Adam, fully_connected/biases/Adam_1, fully_connected/weights, fully_connected/weights/Adam, fully_connected/weights/Adam_1, fully_connected_1/biases, fully_connected_1/biases/Adam, fully_connected_1/biases/Adam_1, fully_connected_1/weights, fully_connected_1/weights/Adam, fully_connected_1/weights/Adam_1, fully_connected_2/biases, fully_connected_2/biases/Adam, fully_connected_2/biases/Adam_1, fully_connected_2/weights, fully_connected_2/weights/Adam, fully_connected_2/weights/Adam_1)]]\cf1\highlight1 
\par 
\par \cf0\highlight0 Caused by op 'save/SaveV2', defined at:\cf1\highlight1 
\par \cf0\highlight0   File "tipr-third-assignment/src/main.py", line 242, in <module>\cf1\highlight1 
\par \cf0\highlight0     saver = tf.train.Saver()\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1281, in __init__\cf1\highlight1 
\par \cf0\highlight0     self.build()\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1293, in build\cf1\highlight1 
\par \cf0\highlight0     self._build(self._filename, build_save=True, build_restore=True)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1330, in _build\cf1\highlight1 
\par \cf0\highlight0     build_save=build_save, build_restore=build_restore)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 775, in _build_internal\cf1\highlight1 
\par \cf0\highlight0     save_tensor = self._AddSaveOps(filename_tensor, saveables)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 275, in _AddSaveOps\cf1\highlight1 
\par \cf0\highlight0     save = self.save_op(filename_tensor, saveables)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 193, in save_op\cf1\highlight1 
\par \cf0\highlight0     tensors)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1687, in save_v2\cf1\highlight1 
\par \cf0\highlight0     shape_and_slices=shape_and_slices, tensors=tensors, name=name)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper\cf1\highlight1 
\par \cf0\highlight0     op_def=op_def)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func\cf1\highlight1 
\par \cf0\highlight0     return func(*args, **kwargs)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op\cf1\highlight1 
\par \cf0\highlight0     op_def=op_def)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__\cf1\highlight1 
\par \cf0\highlight0     self._traceback = tf_stack.extract_stack()\cf1\highlight1 
\par 
\par \cf0\highlight0 NotFoundError (see above for traceback): ../Models/Fashion-MNIST; No such file or directory\cf1\highlight1 
\par \cf0\highlight0          [[Node: save/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, W0, W0/Adam, W0/Adam_1, W1, W1/Adam, W1/Adam_1, batch_normalization/beta, batch_normalization/beta/Adam, batch_normalization/beta/Adam_1, batch_normalization/gamma, batch_normalization/gamma/Adam, batch_normalization/gamma/Adam_1, batch_normalization/moving_mean, batch_normalization/moving_variance, batch_normalization_1/beta, batch_normalization_1/beta/Adam, batch_normalization_1/beta/Adam_1, batch_normalization_1/gamma, batch_normalization_1/gamma/Adam, batch_normalization_1/gamma/Adam_1, batch_normalization_1/moving_mean, batch_normalization_1/moving_variance, batch_normalization_2/beta, batch_normalization_2/beta/Adam, batch_normalization_2/beta/Adam_1, batch_normalization_2/gamma, batch_normalization_2/gamma/Adam, batch_normalization_2/gamma/Adam_1, batch_normalization_2/moving_mean, batch_normalization_2/moving_variance, batch_normalization_3/beta, batch_normalization_3/beta/Adam, batch_normalization_3/beta/Adam_1, batch_normalization_3/gamma, batch_normalization_3/gamma/Adam, batch_normalization_3/gamma/Adam_1, batch_normalization_3/moving_mean, batch_normalization_3/moving_variance, beta1_power, beta2_power, fully_connected/biases, fully_connected/biases/Adam, fully_connected/biases/Adam_1, fully_connected/weights, fully_connected/weights/Adam, fully_connected/weights/Adam_1, fully_connected_1/biases, fully_connected_1/biases/Adam, fully_connected_1/biases/Adam_1, fully_connected_1/weights, fully_connected_1/weights/Adam, fully_connected_1/weights/Adam_1, fully_connected_2/biases, fully_connected_2/biases/Adam, fully_connected_2/biases/Adam_1, fully_connected_2/weights, fully_connected_2/weights/Adam, fully_connected_2/weights/Adam_1)]]\cf1\highlight1 
\par 
\par 
\par \cf0\highlight0 During handling of the above exception, another exception occurred:\cf1\highlight1 
\par 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight1 
\par \cf0\highlight0   File "tipr-third-assignment/src/main.py", line 243, in <module>\cf1\highlight1 
\par \cf0\highlight0     save_path = saver.save(sess, save_model_path)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1637, in save\cf1\highlight1 
\par \cf0\highlight0     raise exc\cf1\highlight1 
\par \cf0\highlight0 ValueError: Parent directory of ../Models/Fashion-MNIST/Fashion-MNIST doesn't exist, can't save.\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~$ python3 "tipr-third-assignment/src/main.py" --test-data tipr-third-assignment/data --dataset Fashion-MNIST\cf1\highlight1 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight1 
\par \cf0\highlight0   File "tipr-third-assignment/src/main.py", line 247, in <module>\cf1\highlight1 
\par \cf0\highlight0     saver = tf.train.import_meta_graph(save_model_path + '.meta')\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1931, in import_meta_graph\cf1\highlight1 
\par \cf0\highlight0     meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 633, in read_meta_graph_file\cf1\highlight1 
\par \cf0\highlight0     raise IOError("File %s does not exist." % filename)\cf1\highlight1 
\par \cf0\highlight0 OSError: File ../Modelsfinal/Fashion-MNIST.meta does not exist.\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~$ pwd\cf1\highlight1 
\par \cf0\highlight0 /home2/e1-313-15127\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~$ cd tipr-third-assignment\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ ls\cf1\highlight1 
\par \cf0\highlight0 Assignment.pdf  \cf6 data\cf0   LICENSE  \cf6 Models\cf0   \cf6 Modelsfinal\cf0   \cf6 Output files\cf0   \cf6 Output plots\cf0   README.md  \cf6 Report\cf0   \cf6 src\cf0   virtualenv_tutorial.md\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --test-data tipr-third-assignment/data --dataset Fashion-MNIST\cf1\highlight1 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight1 
\par \cf0\highlight0   File "src/main.py", line 247, in <module>\cf1\highlight1 
\par \cf0\highlight0     saver = tf.train.import_meta_graph(save_model_path + '.meta')\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1931, in import_meta_graph\cf1\highlight1 
\par \cf0\highlight0     meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 633, in read_meta_graph_file\cf1\highlight1 
\par \cf0\highlight0     raise IOError("File %s does not exist." % filename)\cf1\highlight1 
\par \cf0\highlight0 OSError: File ../Modelsfinal/Fashion-MNIST.meta does not exist.\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --test-data tipr-third-assignment/data --dataset Fashion-MNIST\cf1\highlight1 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight1 
\par \cf0\highlight0   File "src/main.py", line 247, in <module>\cf1\highlight1 
\par \cf0\highlight0     saver = tf.train.import_meta_graph(save_model_path + '.meta')\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1931, in import_meta_graph\cf1\highlight1 
\par \cf0\highlight0     meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 633, in read_meta_graph_file\cf1\highlight1 
\par \cf0\highlight0     raise IOError("File %s does not exist." % filename)\cf1\highlight1 
\par \cf0\highlight0 OSError: File ../Modelsfinal/Fashion-MNIST.meta does not exist.\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --test-data tipr-third-assignment/data --dataset Fashion-MNIST\cf1\highlight1 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight1 
\par \cf0\highlight0   File "src/main.py", line 247, in <module>\cf1\highlight1 
\par \cf0\highlight0     saver = tf.train.import_meta_graph(save_model_path + '.meta')\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1931, in import_meta_graph\cf1\highlight1 
\par \cf0\highlight0     meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 633, in read_meta_graph_file\cf1\highlight1 
\par \cf0\highlight0     raise IOError("File %s does not exist." % filename)\cf1\highlight1 
\par \cf0\highlight0 OSError: File Modelsfinal/Fashion-MNIST.meta does not exist.\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --test-data tipr-third-assignment/data --dataset Fashion-MNIST\cf1\highlight1 
\par \cf0\highlight0   File "src/main.py", line 201\cf1\highlight1 
\par \cf0\highlight0     save_model_path = 'Modelsfinal/' + datasetName '/' + datasetName\cf1\highlight1 
\par \cf0\highlight0                                                      ^\cf1\highlight1 
\par \cf0\highlight0 SyntaxError: invalid syntax\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --test-data tipr-third-assignment/data --dataset Fashion-MNIST\cf1\highlight1 
\par \cf0\highlight0 2019-03-20 17:40:05.812152: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\cf1\highlight1 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight1 
\par \cf0\highlight0   File "src/main.py", line 256, in <module>\cf1\highlight1 
\par \cf0\highlight0     saver.restore(sesst,tf.train.latest_checkpoint('Modelsfinal' + '/' + datasetName))\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1841, in latest_checkpoint\cf1\highlight1 
\par \cf0\highlight0     if file_io.get_matching_files(v2_path) or file_io.get_matching_files(\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 342, in get_matching_files\cf1\highlight1 
\par \cf0\highlight0     for single_filename in filename\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__\cf1\highlight1 
\par \cf0\highlight0     c_api.TF_GetCode(self.status.status))\cf1\highlight1 
\par \cf0\highlight0 tensorflow.python.framework.errors_impl.NotFoundError: Modelsfinal/Fashion-MNIST/Modelsfinal/Fashion-MNIST; No such file or directory\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --test-data tipr-third-assignment/data --dataset Fashion-MNIST\cf1\highlight1 
\par \cf0\highlight0 2019-03-20 17:43:01.905173: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\cf1\highlight1 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight1 
\par \cf0\highlight0   File "src/main.py", line 256, in <module>\cf1\highlight1 
\par \cf0\highlight0     saver.restore(sesst,tf.train.latest_checkpoint('Modelsfinal'))\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1713, in restore\cf1\highlight1 
\par \cf0\highlight0     raise ValueError("Can't load save_path when it is None.")\cf1\highlight1 
\par \cf0\highlight0 ValueError: Can't load save_path when it is None.\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --test-data tipr-third-assignment/data --dataset Fashion-MNIST\cf1\highlight1 
\par \cf0\highlight0 2019-03-20 17:44:28.103272: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\cf1\highlight1 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight1 
\par \cf0\highlight0   File "src/main.py", line 256, in <module>\cf1\highlight1 
\par \cf0\highlight0     saver.restore(sesst,tf.train.latest_checkpoint('Modelsfinal' + '/' + datasetName))\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1841, in latest_checkpoint\cf1\highlight1 
\par \cf0\highlight0     if file_io.get_matching_files(v2_path) or file_io.get_matching_files(\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 342, in get_matching_files\cf1\highlight1 
\par \cf0\highlight0     for single_filename in filename\cf1\highlight1 
\par \cf0\highlight0   File "/home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__\cf1\highlight1 
\par \cf0\highlight0     c_api.TF_GetCode(self.status.status))\cf1\highlight1 
\par \cf0\highlight0 tensorflow.python.framework.errors_impl.NotFoundError: Modelsfinal/Fashion-MNIST/Modelsfinal/Fashion-MNIST; No such file or directory\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --test-data tipr-third-assignment/data --dataset Fashion-MNIST\cf1\highlight1 
\par \cf0\highlight0 2019-03-20 17:45:58.617473: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From src/main.py:277: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use alternatives such as official/mnist/dataset.py from tensorflow/models.\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please write your own downloading logic.\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:252: _internal_retry.<locals>.wrap.<locals>.wrapped_fn (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use urllib or similar directly.\cf1\highlight1 
\par \cf0\highlight0 Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use tf.data to implement this functionality.\cf1\highlight1 
\par \cf0\highlight0 Extracting tipr-third-assignment/data/Fashion-MNIST/train-images-idx3-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use tf.data to implement this functionality.\cf1\highlight1 
\par \cf0\highlight0 Extracting tipr-third-assignment/data/Fashion-MNIST/train-labels-idx1-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:110: dense_to_one_hot (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use tf.one_hot on tensors.\cf1\highlight1 
\par \cf0\highlight0 Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.\cf1\highlight1 
\par \cf0\highlight0 Extracting tipr-third-assignment/data/Fashion-MNIST/t10k-images-idx3-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.\cf1\highlight1 
\par \cf0\highlight0 Extracting tipr-third-assignment/data/Fashion-MNIST/t10k-labels-idx1-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use alternatives such as official/mnist/dataset.py from tensorflow/models.\cf1\highlight1 
\par \cf0\highlight0 Test accuracy :: 0.10674545454545455\cf1\highlight1 
\par \cf0\highlight0 Test Macro F1 Score:: 0.060977325061403055\cf1\highlight1 
\par \cf0\highlight0 Test Micro F1 Score:: 0.10674545454545456\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --test-data tipr-third-assignment/data --dataset CIFAR-10\cf1\highlight1 
\par \cf0\highlight0 2019-03-20 17:47:16.963059: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\cf1\highlight1 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight1 
\par \cf0\highlight0   File "src/main.py", line 271, in <module>\cf1\highlight1 
\par \cf0\highlight0     picklein = open(file, "rb")\cf1\highlight1 
\par \cf0\highlight0 FileNotFoundError: [Errno 2] No such file or directory: 'tipr-third-assignment/data/CIFAR-10'\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --test-data data --dataset CIFAR-10                   2019-03-20 17:48:26.134154: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\cf1\highlight1 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight1 
\par \cf0\highlight0   File "src/main.py", line 271, in <module>\cf1\highlight1 
\par \cf0\highlight0     picklein = open(file, "rb")\cf1\highlight1 
\par \cf0\highlight0 IsADirectoryError: [Errno 21] Is a directory: 'data/CIFAR-10'\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --test-data tipr-third-assignment/data --dataset CIFAR-10\cf1\highlight1 
\par \cf0\highlight0 2019-03-20 17:52:07.194896: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\cf1\highlight1 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight1 
\par \cf0\highlight0   File "src/main.py", line 272, in <module>\cf1\highlight1 
\par \cf0\highlight0     picklein = open(file, "rb")\cf1\highlight1 
\par \cf0\highlight0 FileNotFoundError: [Errno 2] No such file or directory: 'tipr-third-assignment/data/CIFAR-10/data_batch_5'\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --test-data data --dataset CIFAR-10                   2019-03-20 17:52:47.814514: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\cf1\highlight1 
\par \cf0\highlight0 Test accuracy :: 0.9873\cf1\highlight1 
\par \cf0\highlight0 Test Macro F1 Score:: 0.9873130761537908\cf1\highlight1 
\par \cf0\highlight0 Test Micro F1 Score:: 0.9873\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --test-data data --dataset Fashion-MNIST\cf1\highlight1 
\par \cf0\highlight0 2019-03-20 17:53:25.163890: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From src/main.py:278: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use alternatives such as official/mnist/dataset.py from tensorflow/models.\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please write your own downloading logic.\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use tf.data to implement this functionality.\cf1\highlight1 
\par \cf0\highlight0 Extracting data/Fashion-MNIST/train-images-idx3-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use tf.data to implement this functionality.\cf1\highlight1 
\par \cf0\highlight0 Extracting data/Fashion-MNIST/train-labels-idx1-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:110: dense_to_one_hot (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use tf.one_hot on tensors.\cf1\highlight1 
\par \cf0\highlight0 Extracting data/Fashion-MNIST/t10k-images-idx3-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 Extracting data/Fashion-MNIST/t10k-labels-idx1-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use alternatives such as official/mnist/dataset.py from tensorflow/models.\cf1\highlight1 
\par \cf0\highlight0 Test accuracy :: 0.9771090909090909\cf1\highlight1 
\par \cf0\highlight0 Test Macro F1 Score:: 0.9771407575946511\cf1\highlight1 
\par \cf0\highlight0 Test Micro F1 Score:: 0.9771090909090909\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --train-data data--test-data data --dataset Fashion-MNIST --filter-config [3 3] --activation relu\cf1\highlight1 
\par \cf0\highlight0 usage: main.py [-h] [--train-data TRAIN_DATA] [--test-data TEST_DATA]\cf1\highlight1 
\par \cf0\highlight0                [--dataset DATASET]\cf1\highlight1 
\par \cf0\highlight0                [--filter-config [FILTER_CONFIG [FILTER_CONFIG ...]]]\cf1\highlight1 
\par \cf0\highlight0                [--activation ACTIVATION]\cf1\highlight1 
\par \cf0\highlight0 main.py: error: unrecognized arguments: data\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --train-data data --test-data data --dataset Fashion-MNIST --filter-config [3 3] --activation relu\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From src/main.py:205: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par 
\par \cf0\highlight0 Future major versions of TensorFlow will allow gradients to flow\cf1\highlight1 
\par \cf0\highlight0 into the labels input on backprop by default.\cf1\highlight1 
\par 
\par \cf0\highlight0 See @\{tf.nn.softmax_cross_entropy_with_logits_v2\}.\cf1\highlight1 
\par 
\par \cf0\highlight0 2019-03-20 17:57:14.813365: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\cf1\highlight1 
\par \cf0\highlight0 epoch: 0\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From src/main.py:50: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use alternatives such as official/mnist/dataset.py from tensorflow/models.\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please write your own downloading logic.\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use tf.data to implement this functionality.\cf1\highlight1 
\par \cf0\highlight0 Extracting data/Fashion-MNIST/train-images-idx3-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use tf.data to implement this functionality.\cf1\highlight1 
\par \cf0\highlight0 Extracting data/Fashion-MNIST/train-labels-idx1-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:110: dense_to_one_hot (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use tf.one_hot on tensors.\cf1\highlight1 
\par \cf0\highlight0 Extracting data/Fashion-MNIST/t10k-images-idx3-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 Extracting data/Fashion-MNIST/t10k-labels-idx1-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use alternatives such as official/mnist/dataset.py from tensorflow/models.\cf1\highlight1 
\par \cf0\highlight0 Validation test accuracy :: 0.8883636363636364\cf1\highlight1 
\par \cf0\highlight0 Validation test Macro F1 Score:: 0.8866126873518827\cf1\highlight1 
\par \cf0\highlight0 Validation test Micro F1 Score:: 0.8883636363636364\cf1\highlight1 
\par \cf0\highlight0 Extracting data/Fashion-MNIST/train-images-idx3-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 Extracting data/Fashion-MNIST/train-labels-idx1-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 Extracting data/Fashion-MNIST/t10k-images-idx3-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 Extracting data/Fashion-MNIST/t10k-labels-idx1-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 Test accuracy :: 0.8889818181818182\cf1\highlight1 
\par \cf0\highlight0 Test Macro F1 Score:: 0.8884755774960826\cf1\highlight1 
\par \cf0\highlight0 Test Micro F1 Score:: 0.8889818181818182\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --train-data data --test-data data --dataset CIFAR-10 --filter-config [3 3] --activation relu\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From src/main.py:205: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par 
\par \cf0\highlight0 Future major versions of TensorFlow will allow gradients to flow\cf1\highlight1 
\par \cf0\highlight0 into the labels input on backprop by default.\cf1\highlight1 
\par 
\par \cf0\highlight0 See @\{tf.nn.softmax_cross_entropy_with_logits_v2\}.\cf1\highlight1 
\par 
\par \cf0\highlight0 2019-03-20 18:01:33.907693: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\cf1\highlight1 
\par \cf0\highlight0 epoch: 0\cf1\highlight1 
\par \cf0\highlight0 Validation test accuracy :: 0.508\cf1\highlight1 
\par \cf0\highlight0 Validation test Macro F1 Score:: 0.48453102428725225\cf1\highlight1 
\par \cf0\highlight0 Validation test Micro F1 Score:: 0.508\cf1\highlight1 
\par \cf0\highlight0 Test accuracy :: 0.5146\cf1\highlight1 
\par \cf0\highlight0 Test Macro F1 Score:: 0.49599010923950965\cf1\highlight1 
\par \cf0\highlight0 Test Micro F1 Score:: 0.5146\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --test-data testdata --dataset Fashion-MNIST\cf1\highlight1 
\par \cf0\highlight0 2019-03-20 18:36:39.786712: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From src/main.py:278: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use alternatives such as official/mnist/dataset.py from tensorflow/models.\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please write your own downloading logic.\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use tf.data to implement this functionality.\cf1\highlight1 
\par \cf0\highlight0 Extracting testdata/fashion/train-images-idx3-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use tf.data to implement this functionality.\cf1\highlight1 
\par \cf0\highlight0 Extracting testdata/fashion/train-labels-idx1-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:110: dense_to_one_hot (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use tf.one_hot on tensors.\cf1\highlight1 
\par \cf0\highlight0 Extracting testdata/fashion/t10k-images-idx3-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 Extracting testdata/fashion/t10k-labels-idx1-ubyte.gz\cf1\highlight1 
\par \cf0\highlight0 WARNING:tensorflow:From /home2/e1-313-15127/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\cf1\highlight1 
\par \cf0\highlight0 Instructions for updating:\cf1\highlight1 
\par \cf0\highlight0 Please use alternatives such as official/mnist/dataset.py from tensorflow/models.\cf1\highlight1 
\par \cf0\highlight0 Test accuracy :: 0.9143\cf1\highlight1 
\par \cf0\highlight0 Test Macro F1 Score:: 0.9139834783892404\cf1\highlight1 
\par \cf0\highlight0 Test Micro F1 Score:: 0.9143\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --test-data testdata --dataset CIFAR-10\cf1\highlight1 
\par \cf0\highlight0 2019-03-20 18:38:53.455046: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\cf1\highlight1 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight1 
\par \cf0\highlight0   File "src/main.py", line 272, in <module>\cf1\highlight1 
\par \cf0\highlight0     picklein = open(file, "rb")\cf1\highlight1 
\par \cf0\highlight0 FileNotFoundError: [Errno 2] No such file or directory: 'testdata/CIFAR-10/test_batch'\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --test-data testdatacifar --dataset CIFAR-10\cf1\highlight1 
\par \cf0\highlight0 2019-03-20 18:39:23.649318: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\cf1\highlight1 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight1 
\par \cf0\highlight0   File "src/main.py", line 272, in <module>\cf1\highlight1 
\par \cf0\highlight0     picklein = open(file, "rb")\cf1\highlight1 
\par \cf0\highlight0 FileNotFoundError: [Errno 2] No such file or directory: 'testdatacifar/CIFAR-10/test_batch'\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$ python3 "src/main.py" --test-data testdatacifar --dataset CIFAR-10\cf1\highlight1 
\par \cf0\highlight0 2019-03-20 18:40:37.580617: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\cf1\highlight1 
\par \cf0\highlight0 Test accuracy :: 0.5977\cf1\highlight1 
\par \cf0\highlight0 Test Macro F1 Score:: 0.5996659503602262\cf1\highlight1 
\par \cf0\highlight0 Test Micro F1 Score:: 0.5977\cf1\highlight1 
\par \cf0\highlight0 (tensorflow) e1-313-15127@clserv:~/tipr-third-assignment$\cf1\highlight1 
\par \pard\cf0\highlight0\f2\fs20 
\par }
 